remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ANTI-USERAGENT
description: 反爬虫手段之useragent, 支持安卓苹果PC端各个浏览器的UA随机头, 支持requests, httpx, aiohttp等请求包聚合ja3工具集
show_downloads: true

github:
  zip_url: https://github.com/ihandmine/anti-useragent/archive/refs/tags/1.0.10.zip
  tar_url: https://github.com/ihandmine/anti-useragent/archive/refs/tags/1.0.10.tar.gz
  repository_url: https://github.com/ihandmine/anti-useragent
  owner_url: https://github.com/ihandmine
  owner_url: ihandmine
  is_project_page: true
